version: "2"
services:
  db:
    image: postgres:9.5
  web:
    image: ervilis/speackerfight
    command: gunicorn --workers=2 speakerfight.wsgi -b 0.0.0.0:8000
    ports:
      - "80:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
    depends_on:
      - db
